//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarjeta
    {
        public int ID { get; set; }
        public int Tipo_Tarjeta { get; set; }
        public string Banco { get; set; }
        public string Numero { get; set; }
        public int Mes { get; set; }
        public int Ano { get; set; }
        public Nullable<int> codCliente { get; set; }
    
        public virtual clientes clientes { get; set; }
        public virtual Tipo_Tarjeta Tipo_Tarjeta1 { get; set; }
    }
}
